FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

# Build args for environment variables
ARG VITE_USER_API_URL
ARG VITE_DEED_API_URL
ARG VITE_PINATA_API_URL
ARG VITE_SURVEY_PLAN_API_URL
ARG VITE_PROPERTY_NFT_ADDRESS
ARG VITE_FACTORY_ADDRESS
ARG VITE_FRACTIONAL_ADDESS
ARG VITE_ESCROW_FACTORY_ADDRESS
ARG VITE_DEPLOYER_ADDRESS

# Set them as environment variables for Vite build
ENV VITE_USER_API_URL=$VITE_USER_API_URL
ENV VITE_DEED_API_URL=$VITE_DEED_API_URL
ENV VITE_PINATA_API_URL=$VITE_PINATA_API_URL
ENV VITE_SURVEY_PLAN_API_URL=$VITE_SURVEY_PLAN_API_URL
ENV VITE_PROPERTY_NFT_ADDRESS=$VITE_PROPERTY_NFT_ADDRESS
ENV VITE_FACTORY_ADDRESS=$VITE_FACTORY_ADDRESS
ENV VITE_FRACTIONAL_ADDESS=$VITE_FRACTIONAL_ADDESS
ENV VITE_ESCROW_FACTORY_ADDRESS=$VITE_ESCROW_FACTORY_ADDRESS
ENV VITE_DEPLOYER_ADDRESS=$VITE_DEPLOYER_ADDRESS

RUN yarn build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
