import type { Deed } from "../types/deed";

export const mockDeeds: Deed[] = [
  {
    deedNumber: "D001",
    sides: { North: "D002", South: "River", East: "D004", West: "Road" },
    deedType: { deedType: "Sale", deedNumber: "D001" },
    title: [],
    owners: [{ address: "0xabc123", share: 100 }],
    value: 500000,
    location: [
      { longitude: 80.0, latitude: 6.9 },
      { longitude: 80.2, latitude: 6.9 },
      { longitude: 80.2, latitude: 6.7 },
      { longitude: 80.0, latitude: 6.7 },
      { longitude: 80.0, latitude: 6.9 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Alice",
    ownerNIC: "123456789V",
    ownerAddress: "Colombo",
    ownerPhone: "0771234567",
    landTitleNumber: "LT-001",
    landAddress: "Main Street, Colombo",
    landArea: 20,
    landSizeUnit: "Perches",
    district: "Colombo",
    division: "Colombo 01",
    registrationDate: new Date("2025-09-01"),
  },
  {
    deedNumber: "D002",
    sides: { North: "D003", South: "D001", East: "D005", West: "Forest" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D002" },
    title: [],
    owners: [{ address: "0xdef456", share: 100 }],
    value: 750000,
    location: [
      { longitude: 80.0, latitude: 7.1 },
      { longitude: 80.2, latitude: 7.1 },
      { longitude: 80.2, latitude: 6.9 },
      { longitude: 80.0, latitude: 6.9 },
      { longitude: 80.0, latitude: 7.1 },
    ],
    landType: "Lowland",
    timestamp: Date.now(),
    ownerFullName: "Bob Silva",
    ownerNIC: "987654321V",
    ownerAddress: "Kandy",
    ownerPhone: "0779876543",
    landTitleNumber: "LT-002",
    landAddress: "Temple Road, Kandy",
    landArea: 15,
    landSizeUnit: "Perches",
    district: "Kandy",
    division: "Kandy Central",
    registrationDate: new Date("2025-08-15"),
  },
  {
    deedNumber: "D003",
    sides: { North: "D006", South: "D002", East: "D007", West: "Hill" },
    deedType: { deedType: "Mortgage", deedNumber: "D003" },
    title: [],
    owners: [{ address: "0xghi789", share: 100 }],
    value: 1200000,
    location: [
      { longitude: 80.0, latitude: 7.3 },
      { longitude: 80.2, latitude: 7.3 },
      { longitude: 80.2, latitude: 7.1 },
      { longitude: 80.0, latitude: 7.1 },
      { longitude: 80.0, latitude: 7.3 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Catherine Perera",
    ownerNIC: "456789123V",
    ownerAddress: "Galle",
    ownerPhone: "0774561238",
    landTitleNumber: "LT-003",
    landAddress: "Beach Road, Galle",
    landArea: 30,
    landSizeUnit: "Perches",
    district: "Galle",
    division: "Galle Fort",
    registrationDate: new Date("2025-07-20"),
  },
  {
    deedNumber: "D004",
    sides: { North: "D005", South: "Sea", East: "D008", West: "D001" },
    deedType: { deedType: "Sale", deedNumber: "D004" },
    title: [],
    owners: [{ address: "0xjkl012", share: 100 }],
    value: 650000,
    location: [
      { longitude: 80.2, latitude: 6.9 },
      { longitude: 80.4, latitude: 6.9 },
      { longitude: 80.4, latitude: 6.7 },
      { longitude: 80.2, latitude: 6.7 },
      { longitude: 80.2, latitude: 6.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "David Fernando",
    ownerNIC: "789123456V",
    ownerAddress: "Negombo",
    ownerPhone: "0771597534",
    landTitleNumber: "LT-004",
    landAddress: "Sea Street, Negombo",
    landArea: 25,
    landSizeUnit: "Perches",
    district: "Gampaha",
    division: "Negombo",
    registrationDate: new Date("2025-06-10"),
  },
  {
    deedNumber: "D005",
    sides: { North: "D006", South: "D004", East: "D009", West: "D002" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D005" },
    title: [],
    owners: [{ address: "0xmno345", share: 100 }],
    value: 850000,
    location: [
      { longitude: 80.2, latitude: 7.1 },
      { longitude: 80.4, latitude: 7.1 },
      { longitude: 80.4, latitude: 6.9 },
      { longitude: 80.2, latitude: 6.9 },
      { longitude: 80.2, latitude: 7.1 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Elena Rajapakse",
    ownerNIC: "321654987V",
    ownerAddress: "Matara",
    ownerPhone: "0773698741",
    landTitleNumber: "LT-005",
    landAddress: "Rice Field Lane, Matara",
    landArea: 50,
    landSizeUnit: "Acres",
    district: "Matara",
    division: "Matara South",
    registrationDate: new Date("2025-05-25"),
  },
  {
    deedNumber: "D006",
    sides: { North: "D010", South: "D003", East: "D007", West: "Mountain" },
    deedType: { deedType: "Sale", deedNumber: "D006" },
    title: [],
    owners: [{ address: "0xpqr678", share: 100 }],
    value: 920000,
    location: [
      { longitude: 80.0, latitude: 7.5 },
      { longitude: 80.2, latitude: 7.5 },
      { longitude: 80.2, latitude: 7.3 },
      { longitude: 80.0, latitude: 7.3 },
      { longitude: 80.0, latitude: 7.5 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Frank Jayawardene",
    ownerNIC: "654987321V",
    ownerAddress: "Badulla",
    ownerPhone: "0775547896",
    landTitleNumber: "LT-006",
    landAddress: "Hill View, Badulla",
    landArea: 35,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Badulla Central",
    registrationDate: new Date("2025-04-12"),
  },
  {
    deedNumber: "D007",
    sides: { North: "D011", South: "D003", East: "D012", West: "D006" },
    deedType: { deedType: "Mortgage", deedNumber: "D007" },
    title: [],
    owners: [{ address: "0xstu901", share: 100 }],
    value: 780000,
    location: [
      { longitude: 80.2, latitude: 7.5 },
      { longitude: 80.4, latitude: 7.5 },
      { longitude: 80.4, latitude: 7.3 },
      { longitude: 80.2, latitude: 7.3 },
      { longitude: 80.2, latitude: 7.5 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Grace Wijesinghe",
    ownerNIC: "987321654V",
    ownerAddress: "Ratnapura",
    ownerPhone: "0778965412",
    landTitleNumber: "LT-007",
    landAddress: "Market Street, Ratnapura",
    landArea: 18,
    landSizeUnit: "Perches",
    district: "Ratnapura",
    division: "Ratnapura Town",
    registrationDate: new Date("2025-03-28"),
  },
  {
    deedNumber: "D008",
    sides: { North: "D009", South: "Ocean", East: "D013", West: "D004" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D008" },
    title: [],
    owners: [{ address: "0xvwx234", share: 100 }],
    value: 1100000,
    location: [
      { longitude: 80.4, latitude: 6.9 },
      { longitude: 80.6, latitude: 6.9 },
      { longitude: 80.6, latitude: 6.7 },
      { longitude: 80.4, latitude: 6.7 },
      { longitude: 80.4, latitude: 6.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Henry Gunasekara",
    ownerNIC: "123789456V",
    ownerAddress: "Hambantota",
    ownerPhone: "0772581473",
    landTitleNumber: "LT-008",
    landAddress: "Coast Road, Hambantota",
    landArea: 40,
    landSizeUnit: "Perches",
    district: "Hambantota",
    division: "Hambantota Port",
    registrationDate: new Date("2025-02-14"),
  },
  {
    deedNumber: "D009",
    sides: { North: "D012", South: "D008", East: "D014", West: "D005" },
    deedType: { deedType: "Sale", deedNumber: "D009" },
    title: [],
    owners: [{ address: "0xyza567", share: 100 }],
    value: 690000,
    location: [
      { longitude: 80.4, latitude: 7.1 },
      { longitude: 80.6, latitude: 7.1 },
      { longitude: 80.6, latitude: 6.9 },
      { longitude: 80.4, latitude: 6.9 },
      { longitude: 80.4, latitude: 7.1 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Irene Mendis",
    ownerNIC: "456123789V",
    ownerAddress: "Polonnaruwa",
    ownerPhone: "0777539642",
    landTitleNumber: "LT-009",
    landAddress: "Paddy Field Road, Polonnaruwa",
    landArea: 75,
    landSizeUnit: "Acres",
    district: "Polonnaruwa",
    division: "Polonnaruwa Ancient City",
    registrationDate: new Date("2025-01-30"),
  },
  {
    deedNumber: "D010",
    sides: { North: "D015", South: "D006", East: "D011", West: "Valley" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D010" },
    title: [],
    owners: [{ address: "0xbcd890", share: 100 }],
    value: 830000,
    location: [
      { longitude: 80.0, latitude: 7.7 },
      { longitude: 80.2, latitude: 7.7 },
      { longitude: 80.2, latitude: 7.5 },
      { longitude: 80.0, latitude: 7.5 },
      { longitude: 80.0, latitude: 7.7 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "John Amarasekara",
    ownerNIC: "789456123V",
    ownerAddress: "Nuwara Eliya",
    ownerPhone: "0774862951",
    landTitleNumber: "LT-010",
    landAddress: "Tea Estate Road, Nuwara Eliya",
    landArea: 28,
    landSizeUnit: "Perches",
    district: "Nuwara Eliya",
    division: "Nuwara Eliya Central",
    registrationDate: new Date("2024-12-18"),
  },
  {
    deedNumber: "D011",
    sides: { North: "D016", South: "D007", East: "D017", West: "D010" },
    deedType: { deedType: "Mortgage", deedNumber: "D011" },
    title: [],
    owners: [{ address: "0xefg123", share: 100 }],
    value: 1050000,
    location: [
      { longitude: 80.2, latitude: 7.7 },
      { longitude: 80.4, latitude: 7.7 },
      { longitude: 80.4, latitude: 7.5 },
      { longitude: 80.2, latitude: 7.5 },
      { longitude: 80.2, latitude: 7.7 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Kamani Dissanayake",
    ownerNIC: "321987654V",
    ownerAddress: "Anuradhapura",
    ownerPhone: "0773691478",
    landTitleNumber: "LT-011",
    landAddress: "Sacred City Avenue, Anuradhapura",
    landArea: 22,
    landSizeUnit: "Perches",
    district: "Anuradhapura",
    division: "Anuradhapura Sacred City",
    registrationDate: new Date("2024-11-25"),
  },
  {
    deedNumber: "D012",
    sides: { North: "D017", South: "D007", East: "D018", West: "D011" },
    deedType: { deedType: "Sale", deedNumber: "D012" },
    title: [],
    owners: [{ address: "0xhij456", share: 100 }],
    value: 720000,
    location: [
      { longitude: 80.4, latitude: 7.7 },
      { longitude: 80.6, latitude: 7.7 },
      { longitude: 80.6, latitude: 7.5 },
      { longitude: 80.4, latitude: 7.5 },
      { longitude: 80.4, latitude: 7.7 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Lakshmi Bandara",
    ownerNIC: "654321987V",
    ownerAddress: "Kurunegala",
    ownerPhone: "0778529641",
    landTitleNumber: "LT-012",
    landAddress: "Lake View Road, Kurunegala",
    landArea: 32,
    landSizeUnit: "Perches",
    district: "Kurunegala",
    division: "Kurunegala Central",
    registrationDate: new Date("2024-10-08"),
  },
  {
    deedNumber: "D013",
    sides: { North: "D014", South: "Lagoon", East: "D019", West: "D008" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D013" },
    title: [],
    owners: [{ address: "0xklm789", share: 100 }],
    value: 980000,
    location: [
      { longitude: 80.6, latitude: 6.9 },
      { longitude: 80.8, latitude: 6.9 },
      { longitude: 80.8, latitude: 6.7 },
      { longitude: 80.6, latitude: 6.7 },
      { longitude: 80.6, latitude: 6.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Mahesh Ranasinghe",
    ownerNIC: "987654123V",
    ownerAddress: "Puttalam",
    ownerPhone: "0775286391",
    landTitleNumber: "LT-013",
    landAddress: "Salt Works Road, Puttalam",
    landArea: 45,
    landSizeUnit: "Perches",
    district: "Puttalam",
    division: "Puttalam Lagoon",
    registrationDate: new Date("2024-09-12"),
  },
  {
    deedNumber: "D014",
    sides: { North: "D018", South: "D013", East: "D020", West: "D009" },
    deedType: { deedType: "Mortgage", deedNumber: "D014" },
    title: [],
    owners: [{ address: "0xnop012", share: 100 }],
    value: 620000,
    location: [
      { longitude: 80.6, latitude: 7.1 },
      { longitude: 80.8, latitude: 7.1 },
      { longitude: 80.8, latitude: 6.9 },
      { longitude: 80.6, latitude: 6.9 },
      { longitude: 80.6, latitude: 7.1 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Nilanthi Wickramasinghe",
    ownerNIC: "123456987V",
    ownerAddress: "Monaragala",
    ownerPhone: "0772847395",
    landTitleNumber: "LT-014",
    landAddress: "Farming Lane, Monaragala",
    landArea: 60,
    landSizeUnit: "Acres",
    district: "Monaragala",
    division: "Monaragala East",
    registrationDate: new Date("2024-08-29"),
  },
  {
    deedNumber: "D015",
    sides: { North: "D021", South: "D010", East: "D016", West: "Plateau" },
    deedType: { deedType: "Sale", deedNumber: "D015" },
    title: [],
    owners: [{ address: "0xqrs345", share: 100 }],
    value: 1300000,
    location: [
      { longitude: 80.0, latitude: 7.9 },
      { longitude: 80.2, latitude: 7.9 },
      { longitude: 80.2, latitude: 7.7 },
      { longitude: 80.0, latitude: 7.7 },
      { longitude: 80.0, latitude: 7.9 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Ositha Senanayake",
    ownerNIC: "456789321V",
    ownerAddress: "Bandarawela",
    ownerPhone: "0779384756",
    landTitleNumber: "LT-015",
    landAddress: "Mountain View, Bandarawela",
    landArea: 55,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Bandarawela",
    registrationDate: new Date("2024-07-15"),
  },
  {
    deedNumber: "D016",
    sides: { North: "D022", South: "D011", East: "D017", West: "D015" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D016" },
    title: [],
    owners: [{ address: "0xtuv678", share: 100 }],
    value: 740000,
    location: [
      { longitude: 80.2, latitude: 7.9 },
      { longitude: 80.4, latitude: 7.9 },
      { longitude: 80.4, latitude: 7.7 },
      { longitude: 80.2, latitude: 7.7 },
      { longitude: 80.2, latitude: 7.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Priyanka Gunawardena",
    ownerNIC: "789123654V",
    ownerAddress: "Kalutara",
    ownerPhone: "0774729384",
    landTitleNumber: "LT-016",
    landAddress: "Riverside Drive, Kalutara",
    landArea: 26,
    landSizeUnit: "Perches",
    district: "Kalutara",
    division: "Kalutara South",
    registrationDate: new Date("2024-06-02"),
  },
  {
    deedNumber: "D017",
    sides: { North: "D023", South: "D012", East: "D018", West: "D016" },
    deedType: { deedType: "Mortgage", deedNumber: "D017" },
    title: [],
    owners: [{ address: "0xwxy901", share: 100 }],
    value: 890000,
    location: [
      { longitude: 80.4, latitude: 7.9 },
      { longitude: 80.6, latitude: 7.9 },
      { longitude: 80.6, latitude: 7.7 },
      { longitude: 80.4, latitude: 7.7 },
      { longitude: 80.4, latitude: 7.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Quintus De Silva",
    ownerNIC: "321654789V",
    ownerAddress: "Jaffna",
    ownerPhone: "0771593746",
    landTitleNumber: "LT-017",
    landAddress: "Northern Plaza, Jaffna",
    landArea: 38,
    landSizeUnit: "Perches",
    district: "Jaffna",
    division: "Jaffna Central",
    registrationDate: new Date("2024-05-18"),
  },
  {
    deedNumber: "D018",
    sides: { North: "D024", South: "D014", East: "D020", West: "D017" },
    deedType: { deedType: "Sale", deedNumber: "D018" },
    title: [],
    owners: [{ address: "0xzab234", share: 100 }],
    value: 770000,
    location: [
      { longitude: 80.6, latitude: 7.9 },
      { longitude: 80.8, latitude: 7.9 },
      { longitude: 80.8, latitude: 7.7 },
      { longitude: 80.6, latitude: 7.7 },
      { longitude: 80.6, latitude: 7.9 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Ruwan Herath",
    ownerNIC: "654987123V",
    ownerAddress: "Trincomalee",
    ownerPhone: "0778462951",
    landTitleNumber: "LT-018",
    landAddress: "Harbor Road, Trincomalee",
    landArea: 42,
    landSizeUnit: "Acres",
    district: "Trincomalee",
    division: "Trincomalee Port",
    registrationDate: new Date("2024-04-25"),
  },
  {
    deedNumber: "D019",
    sides: { North: "D020", South: "Bay", East: "D025", West: "D013" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D019" },
    title: [],
    owners: [{ address: "0xcde567", share: 100 }],
    value: 1180000,
    location: [
      { longitude: 80.8, latitude: 6.9 },
      { longitude: 81.0, latitude: 6.9 },
      { longitude: 81.0, latitude: 6.7 },
      { longitude: 80.8, latitude: 6.7 },
      { longitude: 80.8, latitude: 6.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Sanduni Rajapaksa",
    ownerNIC: "987321456V",
    ownerAddress: "Batticaloa",
    ownerPhone: "0773856294",
    landTitleNumber: "LT-019",
    landAddress: "Lagoon View, Batticaloa",
    landArea: 33,
    landSizeUnit: "Perches",
    district: "Batticaloa",
    division: "Batticaloa Central",
    registrationDate: new Date("2024-03-10"),
  },
  {
    deedNumber: "D020",
    sides: { North: "D024", South: "D019", East: "D026", West: "D014" },
    deedType: { deedType: "Mortgage", deedNumber: "D020" },
    title: [],
    owners: [{ address: "0xfgh890", share: 100 }],
    value: 640000,
    location: [
      { longitude: 80.8, latitude: 7.1 },
      { longitude: 81.0, latitude: 7.1 },
      { longitude: 81.0, latitude: 6.9 },
      { longitude: 80.8, latitude: 6.9 },
      { longitude: 80.8, latitude: 7.1 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Thilak Abeysekara",
    ownerNIC: "123789654V",
    ownerAddress: "Ampara",
    ownerPhone: "0775927384",
    landTitleNumber: "LT-020",
    landAddress: "Cultivation Road, Ampara",
    landArea: 85,
    landSizeUnit: "Acres",
    district: "Ampara",
    division: "Ampara East",
    registrationDate: new Date("2024-02-28"),
  },
  {
    deedNumber: "D021",
    sides: { North: "D027", South: "D015", East: "D022", West: "Cliff" },
    deedType: { deedType: "Sale", deedNumber: "D021" },
    title: [],
    owners: [{ address: "0xijk123", share: 100 }],
    value: 1450000,
    location: [
      { longitude: 80.0, latitude: 8.1 },
      { longitude: 80.2, latitude: 8.1 },
      { longitude: 80.2, latitude: 7.9 },
      { longitude: 80.0, latitude: 7.9 },
      { longitude: 80.0, latitude: 8.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Upul Weerasinghe",
    ownerNIC: "456321987V",
    ownerAddress: "Ella",
    ownerPhone: "0774185926",
    landTitleNumber: "LT-021",
    landAddress: "Hilltop Estate, Ella",
    landArea: 48,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Ella",
    registrationDate: new Date("2024-01-15"),
  },
  {
    deedNumber: "D022",
    sides: { North: "D028", South: "D016", East: "D023", West: "D021" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D022" },
    title: [],
    owners: [{ address: "0xlmn456", share: 100 }],
    value: 810000,
    location: [
      { longitude: 80.2, latitude: 8.1 },
      { longitude: 80.4, latitude: 8.1 },
      { longitude: 80.4, latitude: 7.9 },
      { longitude: 80.2, latitude: 7.9 },
      { longitude: 80.2, latitude: 8.1 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Vindya Ratnaweera",
    ownerNIC: "789654321V",
    ownerAddress: "Vavuniya",
    ownerPhone: "0777384625",
    landTitleNumber: "LT-022",
    landAddress: "Central Market, Vavuniya",
    landArea: 24,
    landSizeUnit: "Perches",
    district: "Vavuniya",
    division: "Vavuniya South",
    registrationDate: new Date("2023-12-22"),
  },
  {
    deedNumber: "D023",
    sides: { North: "D029", South: "D017", East: "D024", West: "D022" },
    deedType: { deedType: "Mortgage", deedNumber: "D023" },
    title: [],
    owners: [{ address: "0xopq789", share: 100 }],
    value: 920000,
    location: [
      { longitude: 80.4, latitude: 8.1 },
      { longitude: 80.6, latitude: 8.1 },
      { longitude: 80.6, latitude: 7.9 },
      { longitude: 80.4, latitude: 7.9 },
      { longitude: 80.4, latitude: 8.1 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Wasantha Jayasuriya",
    ownerNIC: "321987456V",
    ownerAddress: "Mannar",
    ownerPhone: "0772639481",
    landTitleNumber: "LT-023",
    landAddress: "Island Road, Mannar",
    landArea: 29,
    landSizeUnit: "Perches",
    district: "Mannar",
    division: "Mannar Island",
    registrationDate: new Date("2023-11-08"),
  },
  {
    deedNumber: "D024",
    sides: { North: "D030", South: "D018", East: "D026", West: "D023" },
    deedType: { deedType: "Sale", deedNumber: "D024" },
    title: [],
    owners: [{ address: "0xrst012", share: 100 }],
    value: 690000,
    location: [
      { longitude: 80.6, latitude: 8.1 },
      { longitude: 80.8, latitude: 8.1 },
      { longitude: 80.8, latitude: 7.9 },
      { longitude: 80.6, latitude: 7.9 },
      { longitude: 80.6, latitude: 8.1 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Ximena Rodrigo",
    ownerNIC: "654123987V",
    ownerAddress: "Mullaitivu",
    ownerPhone: "0778529374",
    landTitleNumber: "LT-024",
    landAddress: "Coastal Farm, Mullaitivu",
    landArea: 70,
    landSizeUnit: "Acres",
    district: "Mullaitivu",
    division: "Mullaitivu Central",
    registrationDate: new Date("2023-10-14"),
  },
  {
    deedNumber: "D025",
    sides: { North: "D026", South: "Strait", East: "D031", West: "D019" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D025" },
    title: [],
    owners: [{ address: "0xuvy345", share: 100 }],
    value: 1250000,
    location: [
      { longitude: 81.0, latitude: 6.9 },
      { longitude: 81.2, latitude: 6.9 },
      { longitude: 81.2, latitude: 6.7 },
      { longitude: 81.0, latitude: 6.7 },
      { longitude: 81.0, latitude: 6.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Yasmin Samaraweera",
    ownerNIC: "987456123V",
    ownerAddress: "Kilinochchi",
    ownerPhone: "0775862394",
    landTitleNumber: "LT-025",
    landAddress: "Trade Center, Kilinochchi",
    landArea: 36,
    landSizeUnit: "Perches",
    district: "Kilinochchi",
    division: "Kilinochchi Central",
    registrationDate: new Date("2023-09-30"),
  },
  {
    deedNumber: "D026",
    sides: { North: "D030", South: "D025", East: "D032", West: "D020" },
    deedType: { deedType: "Mortgage", deedNumber: "D026" },
    title: [],
    owners: [{ address: "0xwxz678", share: 100 }],
    value: 580000,
    location: [
      { longitude: 81.0, latitude: 7.1 },
      { longitude: 81.2, latitude: 7.1 },
      { longitude: 81.2, latitude: 6.9 },
      { longitude: 81.0, latitude: 6.9 },
      { longitude: 81.0, latitude: 7.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Zoysa Wickremasinghe",
    ownerNIC: "123654789V",
    ownerAddress: "Kegalle",
    ownerPhone: "0774917385",
    landTitleNumber: "LT-026",
    landAddress: "Rubber Estate, Kegalle",
    landArea: 65,
    landSizeUnit: "Acres",
    district: "Kegalle",
    division: "Kegalle East",
    registrationDate: new Date("2023-08-16"),
  },
  {
    deedNumber: "D027",
    sides: { North: "D033", South: "D021", East: "D028", West: "Gorge" },
    deedType: { deedType: "Sale", deedNumber: "D027" },
    title: [],
    owners: [{ address: "0xabc901", share: 100 }],
    value: 1560000,
    location: [
      { longitude: 80.0, latitude: 8.3 },
      { longitude: 80.2, latitude: 8.3 },
      { longitude: 80.2, latitude: 8.1 },
      { longitude: 80.0, latitude: 8.1 },
      { longitude: 80.0, latitude: 8.3 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Asanka Perera",
    ownerNIC: "456789654V",
    ownerAddress: "Hatton",
    ownerPhone: "0771729384",
    landTitleNumber: "LT-027",
    landAddress: "Tea Garden Heights, Hatton",
    landArea: 52,
    landSizeUnit: "Perches",
    district: "Nuwara Eliya",
    division: "Hatton",
    registrationDate: new Date("2023-07-25"),
  },
  {
    deedNumber: "D028",
    sides: { North: "D034", South: "D022", East: "D029", West: "D027" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D028" },
    title: [],
    owners: [{ address: "0xdef234", share: 100 }],
    value: 870000,
    location: [
      { longitude: 80.2, latitude: 8.3 },
      { longitude: 80.4, latitude: 8.3 },
      { longitude: 80.4, latitude: 8.1 },
      { longitude: 80.2, latitude: 8.1 },
      { longitude: 80.2, latitude: 8.3 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Buddhika Silva",
    ownerNIC: "789321654V",
    ownerAddress: "Dambulla",
    ownerPhone: "0778394625",
    landTitleNumber: "LT-028",
    landAddress: "Cave Temple Road, Dambulla",
    landArea: 27,
    landSizeUnit: "Perches",
    district: "Matale",
    division: "Dambulla",
    registrationDate: new Date("2023-06-12"),
  },
  {
    deedNumber: "D029",
    sides: { North: "D035", South: "D023", East: "D030", West: "D028" },
    deedType: { deedType: "Mortgage", deedNumber: "D029" },
    title: [],
    owners: [{ address: "0xghi567", share: 100 }],
    value: 1020000,
    location: [
      { longitude: 80.4, latitude: 8.3 },
      { longitude: 80.6, latitude: 8.3 },
      { longitude: 80.6, latitude: 8.1 },
      { longitude: 80.4, latitude: 8.1 },
      { longitude: 80.4, latitude: 8.3 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Chamara Bandara",
    ownerNIC: "321456789V",
    ownerAddress: "Sigiriya",
    ownerPhone: "0775182736",
    landTitleNumber: "LT-029",
    landAddress: "Heritage Plaza, Sigiriya",
    landArea: 31,
    landSizeUnit: "Perches",
    district: "Matale",
    division: "Sigiriya",
    registrationDate: new Date("2023-05-28"),
  },
  {
    deedNumber: "D030",
    sides: { North: "D036", South: "D024", East: "D032", West: "D029" },
    deedType: { deedType: "Sale", deedNumber: "D030" },
    title: [],
    owners: [{ address: "0xjkl890", share: 100 }],
    value: 750000,
    location: [
      { longitude: 80.6, latitude: 8.3 },
      { longitude: 80.8, latitude: 8.3 },
      { longitude: 80.8, latitude: 8.1 },
      { longitude: 80.6, latitude: 8.1 },
      { longitude: 80.6, latitude: 8.3 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Dilini Gamage",
    ownerNIC: "654789321V",
    ownerAddress: "Nawalapitiya",
    ownerPhone: "0772958374",
    landTitleNumber: "LT-030",
    landAddress: "Plantation Road, Nawalapitiya",
    landArea: 58,
    landSizeUnit: "Acres",
    district: "Kandy",
    division: "Nawalapitiya",
    registrationDate: new Date("2023-04-15"),
  },
  {
    deedNumber: "D031",
    sides: { North: "D032", South: "Peninsula", East: "D037", West: "D025" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D031" },
    title: [],
    owners: [{ address: "0xmno123", share: 100 }],
    value: 1380000,
    location: [
      { longitude: 81.2, latitude: 6.9 },
      { longitude: 81.4, latitude: 6.9 },
      { longitude: 81.4, latitude: 6.7 },
      { longitude: 81.2, latitude: 6.7 },
      { longitude: 81.2, latitude: 6.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Eranga Dissanayake",
    ownerNIC: "987123456V",
    ownerAddress: "Point Pedro",
    ownerPhone: "0777295384",
    landTitleNumber: "LT-031",
    landAddress: "Peninsula View, Point Pedro",
    landArea: 41,
    landSizeUnit: "Perches",
    district: "Jaffna",
    division: "Point Pedro",
    registrationDate: new Date("2023-03-22"),
  },
  {
    deedNumber: "D032",
    sides: { North: "D036", South: "D031", East: "D038", West: "D026" },
    deedType: { deedType: "Mortgage", deedNumber: "D032" },
    title: [],
    owners: [{ address: "0xpqr456", share: 100 }],
    value: 670000,
    location: [
      { longitude: 81.2, latitude: 7.1 },
      { longitude: 81.4, latitude: 7.1 },
      { longitude: 81.4, latitude: 6.9 },
      { longitude: 81.2, latitude: 6.9 },
      { longitude: 81.2, latitude: 7.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Fathima Nazeer",
    ownerNIC: "123987654V",
    ownerAddress: "Akkaraipattu",
    ownerPhone: "0774638291",
    landTitleNumber: "LT-032",
    landAddress: "Hillock Estate, Akkaraipattu",
    landArea: 47,
    landSizeUnit: "Acres",
    district: "Ampara",
    division: "Akkaraipattu",
    registrationDate: new Date("2023-02-08"),
  },
  {
    deedNumber: "D033",
    sides: { North: "D039", South: "D027", East: "D034", West: "Ridge" },
    deedType: { deedType: "Sale", deedNumber: "D033" },
    title: [],
    owners: [{ address: "0xstu789", share: 100 }],
    value: 1680000,
    location: [
      { longitude: 80.0, latitude: 8.5 },
      { longitude: 80.2, latitude: 8.5 },
      { longitude: 80.2, latitude: 8.3 },
      { longitude: 80.0, latitude: 8.3 },
      { longitude: 80.0, latitude: 8.5 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Gayan Rajapakse",
    ownerNIC: "456654321V",
    ownerAddress: "Haputale",
    ownerPhone: "0771847392",
    landTitleNumber: "LT-033",
    landAddress: "Ridge View Estate, Haputale",
    landArea: 63,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Haputale",
    registrationDate: new Date("2023-01-18"),
  },
  {
    deedNumber: "D034",
    sides: { North: "D040", South: "D028", East: "D035", West: "D033" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D034" },
    title: [],
    owners: [{ address: "0xvwx012", share: 100 }],
    value: 930000,
    location: [
      { longitude: 80.2, latitude: 8.5 },
      { longitude: 80.4, latitude: 8.5 },
      { longitude: 80.4, latitude: 8.3 },
      { longitude: 80.2, latitude: 8.3 },
      { longitude: 80.2, latitude: 8.5 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Hiruni Senanayake",
    ownerNIC: "789456987V",
    ownerAddress: "Welimada",
    ownerPhone: "0775927384",
    landTitleNumber: "LT-034",
    landAddress: "Market Square, Welimada",
    landArea: 28,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Welimada",
    registrationDate: new Date("2022-12-28"),
  },
  {
    deedNumber: "D035",
    sides: { North: "D041", South: "D029", East: "D036", West: "D034" },
    deedType: { deedType: "Mortgage", deedNumber: "D035" },
    title: [],
    owners: [{ address: "0xyza345", share: 100 }],
    value: 1160000,
    location: [
      { longitude: 80.4, latitude: 8.5 },
      { longitude: 80.6, latitude: 8.5 },
      { longitude: 80.6, latitude: 8.3 },
      { longitude: 80.4, latitude: 8.3 },
      { longitude: 80.4, latitude: 8.5 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Indika Weerasinghe",
    ownerNIC: "321789654V",
    ownerAddress: "Mahiyanganaya",
    ownerPhone: "0778364925",
    landTitleNumber: "LT-035",
    landAddress: "River Bank Road, Mahiyanganaya",
    landArea: 34,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Mahiyanganaya",
    registrationDate: new Date("2022-11-14"),
  },
  {
    deedNumber: "D036",
    sides: { North: "D042", South: "D030", East: "D038", West: "D035" },
    deedType: { deedType: "Sale", deedNumber: "D036" },
    title: [],
    owners: [{ address: "0xbcd678", share: 100 }],
    value: 820000,
    location: [
      { longitude: 80.6, latitude: 8.5 },
      { longitude: 80.8, latitude: 8.5 },
      { longitude: 80.8, latitude: 8.3 },
      { longitude: 80.6, latitude: 8.3 },
      { longitude: 80.6, latitude: 8.5 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Janaki Mendis",
    ownerNIC: "654321789V",
    ownerAddress: "Passara",
    ownerPhone: "0772519374",
    landTitleNumber: "LT-036",
    landAddress: "Cultivation Valley, Passara",
    landArea: 72,
    landSizeUnit: "Acres",
    district: "Badulla",
    division: "Passara",
    registrationDate: new Date("2022-10-30"),
  },
  {
    deedNumber: "D037",
    sides: { North: "D038", South: "Channel", East: "D043", West: "D031" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D037" },
    title: [],
    owners: [{ address: "0xefg901", share: 100 }],
    value: 1470000,
    location: [
      { longitude: 81.4, latitude: 6.9 },
      { longitude: 81.6, latitude: 6.9 },
      { longitude: 81.6, latitude: 6.7 },
      { longitude: 81.4, latitude: 6.7 },
      { longitude: 81.4, latitude: 6.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Kumara Wickremasinghe",
    ownerNIC: "987654987V",
    ownerAddress: "Kalmunai",
    ownerPhone: "0779284635",
    landTitleNumber: "LT-037",
    landAddress: "Port Complex, Kalmunai",
    landArea: 39,
    landSizeUnit: "Perches",
    district: "Ampara",
    division: "Kalmunai",
    registrationDate: new Date("2022-09-16"),
  },
  {
    deedNumber: "D038",
    sides: { North: "D042", South: "D037", East: "D044", West: "D032" },
    deedType: { deedType: "Mortgage", deedNumber: "D038" },
    title: [],
    owners: [{ address: "0xhij234", share: 100 }],
    value: 710000,
    location: [
      { longitude: 81.4, latitude: 7.1 },
      { longitude: 81.6, latitude: 7.1 },
      { longitude: 81.6, latitude: 6.9 },
      { longitude: 81.4, latitude: 6.9 },
      { longitude: 81.4, latitude: 7.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Lasitha Gunasekara",
    ownerNIC: "123456654V",
    ownerAddress: "Dehiattakandiya",
    ownerPhone: "0774827395",
    landTitleNumber: "LT-038",
    landAddress: "Highland Estate, Dehiattakandiya",
    landArea: 51,
    landSizeUnit: "Acres",
    district: "Ampara",
    division: "Dehiattakandiya",
    registrationDate: new Date("2022-08-25"),
  },
  {
    deedNumber: "D039",
    sides: { North: "D045", South: "D033", East: "D040", West: "Peak" },
    deedType: { deedType: "Sale", deedNumber: "D039" },
    title: [],
    owners: [{ address: "0xklm567", share: 100 }],
    value: 1790000,
    location: [
      { longitude: 80.0, latitude: 8.7 },
      { longitude: 80.2, latitude: 8.7 },
      { longitude: 80.2, latitude: 8.5 },
      { longitude: 80.0, latitude: 8.5 },
      { longitude: 80.0, latitude: 8.7 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Malini Rajapakse",
    ownerNIC: "456987123V",
    ownerAddress: "Ohiya",
    ownerPhone: "0771639485",
    landTitleNumber: "LT-039",
    landAddress: "Peak View Heights, Ohiya",
    landArea: 68,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Ohiya",
    registrationDate: new Date("2022-07-12"),
  },
  {
    deedNumber: "D040",
    sides: { North: "D046", South: "D034", East: "D041", West: "D039" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D040" },
    title: [],
    owners: [{ address: "0xnop890", share: 100 }],
    value: 1040000,
    location: [
      { longitude: 80.2, latitude: 8.7 },
      { longitude: 80.4, latitude: 8.7 },
      { longitude: 80.4, latitude: 8.5 },
      { longitude: 80.2, latitude: 8.5 },
      { longitude: 80.2, latitude: 8.7 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Nuwan Senanayake",
    ownerNIC: "789123987V",
    ownerAddress: "Koslanda",
    ownerPhone: "0778529641",
    landTitleNumber: "LT-040",
    landAddress: "Valley View, Koslanda",
    landArea: 32,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Koslanda",
    registrationDate: new Date("2022-06-28"),
  },
  {
    deedNumber: "D041",
    sides: { North: "D047", South: "D035", East: "D042", West: "D040" },
    deedType: { deedType: "Mortgage", deedNumber: "D041" },
    title: [],
    owners: [{ address: "0xqrs123", share: 100 }],
    value: 1290000,
    location: [
      { longitude: 80.4, latitude: 8.7 },
      { longitude: 80.6, latitude: 8.7 },
      { longitude: 80.6, latitude: 8.5 },
      { longitude: 80.4, latitude: 8.5 },
      { longitude: 80.4, latitude: 8.7 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Oshen Gamage",
    ownerNIC: "321654123V",
    ownerAddress: "Beragala",
    ownerPhone: "0775184729",
    landTitleNumber: "LT-041",
    landAddress: "Mountain Plaza, Beragala",
    landArea: 37,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Beragala",
    registrationDate: new Date("2022-05-15"),
  },
  {
    deedNumber: "D042",
    sides: { North: "D048", South: "D036", East: "D044", West: "D041" },
    deedType: { deedType: "Sale", deedNumber: "D042" },
    title: [],
    owners: [{ address: "0xtuv456", share: 100 }],
    value: 880000,
    location: [
      { longitude: 80.6, latitude: 8.7 },
      { longitude: 80.8, latitude: 8.7 },
      { longitude: 80.8, latitude: 8.5 },
      { longitude: 80.6, latitude: 8.5 },
      { longitude: 80.6, latitude: 8.7 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Pradeep Wijesinghe",
    ownerNIC: "654789654V",
    ownerAddress: "Moneragala",
    ownerPhone: "0773947285",
    landTitleNumber: "LT-042",
    landAddress: "Farming Hills, Moneragala",
    landArea: 66,
    landSizeUnit: "Acres",
    district: "Moneragala",
    division: "Moneragala Central",
    registrationDate: new Date("2022-04-22"),
  },
  {
    deedNumber: "D043",
    sides: { North: "D044", South: "Inlet", East: "D049", West: "D037" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D043" },
    title: [],
    owners: [{ address: "0xwxy789", share: 100 }],
    value: 1590000,
    location: [
      { longitude: 81.6, latitude: 6.9 },
      { longitude: 81.8, latitude: 6.9 },
      { longitude: 81.8, latitude: 6.7 },
      { longitude: 81.6, latitude: 6.7 },
      { longitude: 81.6, latitude: 6.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Qadri Mohamed",
    ownerNIC: "987321789V",
    ownerAddress: "Sammanthurai",
    ownerPhone: "0771859463",
    landTitleNumber: "LT-043",
    landAddress: "Waterfront Villas, Sammanthurai",
    landArea: 44,
    landSizeUnit: "Perches",
    district: "Ampara",
    division: "Sammanthurai",
    registrationDate: new Date("2022-03-08"),
  },
  {
    deedNumber: "D044",
    sides: { North: "D048", South: "D043", East: "D050", West: "D038" },
    deedType: { deedType: "Mortgage", deedNumber: "D044" },
    title: [],
    owners: [{ address: "0xzab012", share: 100 }],
    value: 760000,
    location: [
      { longitude: 81.6, latitude: 7.1 },
      { longitude: 81.8, latitude: 7.1 },
      { longitude: 81.8, latitude: 6.9 },
      { longitude: 81.6, latitude: 6.9 },
      { longitude: 81.6, latitude: 7.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Rasika Bandara",
    ownerNIC: "123789987V",
    ownerAddress: "Damana",
    ownerPhone: "0776284935",
    landTitleNumber: "LT-044",
    landAddress: "Forest Edge, Damana",
    landArea: 56,
    landSizeUnit: "Acres",
    district: "Ampara",
    division: "Damana",
    registrationDate: new Date("2022-02-14"),
  },
  {
    deedNumber: "D045",
    sides: { North: "Summit", South: "D039", East: "D046", West: "Escarpment" },
    deedType: { deedType: "Sale", deedNumber: "D045" },
    title: [],
    owners: [{ address: "0xcde345", share: 100 }],
    value: 1950000,
    location: [
      { longitude: 80.0, latitude: 8.9 },
      { longitude: 80.2, latitude: 8.9 },
      { longitude: 80.2, latitude: 8.7 },
      { longitude: 80.0, latitude: 8.7 },
      { longitude: 80.0, latitude: 8.9 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Saman Perera",
    ownerNIC: "456321654V",
    ownerAddress: "Horton Plains",
    ownerPhone: "0774926385",
    landTitleNumber: "LT-045",
    landAddress: "Summit View Estate, Horton Plains",
    landArea: 78,
    landSizeUnit: "Perches",
    district: "Nuwara Eliya",
    division: "Horton Plains",
    registrationDate: new Date("2022-01-25"),
  },
  {
    deedNumber: "D046",
    sides: { North: "Plateau", South: "D040", East: "D047", West: "D045" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D046" },
    title: [],
    owners: [{ address: "0xfgh678", share: 100 }],
    value: 1170000,
    location: [
      { longitude: 80.2, latitude: 8.9 },
      { longitude: 80.4, latitude: 8.9 },
      { longitude: 80.4, latitude: 8.7 },
      { longitude: 80.2, latitude: 8.7 },
      { longitude: 80.2, latitude: 8.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Tharanga Jayasuriya",
    ownerNIC: "789654456V",
    ownerAddress: "Poonagala",
    ownerPhone: "0777394628",
    landTitleNumber: "LT-046",
    landAddress: "Plateau Shopping Center, Poonagala",
    landArea: 35,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Poonagala",
    registrationDate: new Date("2021-12-10"),
  },
  {
    deedNumber: "D047",
    sides: { North: "Highland", South: "D041", East: "D048", West: "D046" },
    deedType: { deedType: "Mortgage", deedNumber: "D047" },
    title: [],
    owners: [{ address: "0xijk901", share: 100 }],
    value: 1420000,
    location: [
      { longitude: 80.4, latitude: 8.9 },
      { longitude: 80.6, latitude: 8.9 },
      { longitude: 80.6, latitude: 8.7 },
      { longitude: 80.4, latitude: 8.7 },
      { longitude: 80.4, latitude: 8.9 },
    ],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Udara Wickramasinghe",
    ownerNIC: "321987789V",
    ownerAddress: "Lunugala",
    ownerPhone: "0772859374",
    landTitleNumber: "LT-047",
    landAddress: "Highland Paradise, Lunugala",
    landArea: 46,
    landSizeUnit: "Perches",
    district: "Badulla",
    division: "Lunugala",
    registrationDate: new Date("2021-11-18"),
  },
  {
    deedNumber: "D048",
    sides: { North: "Forest", South: "D042", East: "D050", West: "D047" },
    deedType: { deedType: "Sale", deedNumber: "D048" },
    title: [],
    owners: [{ address: "0xlmn234", share: 100 }],
    value: 950000,
    location: [
      { longitude: 80.6, latitude: 8.9 },
      { longitude: 80.8, latitude: 8.9 },
      { longitude: 80.8, latitude: 8.7 },
      { longitude: 80.6, latitude: 8.7 },
      { longitude: 80.6, latitude: 8.9 },
    ],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Vindya Senanayake",
    ownerNIC: "654123321V",
    ownerAddress: "Bibila",
    ownerPhone: "0775927481",
    landTitleNumber: "LT-048",
    landAddress: "Forest Edge Farm, Bibila",
    landArea: 82,
    landSizeUnit: "Acres",
    district: "Moneragala",
    division: "Bibila",
    registrationDate: new Date("2021-10-26"),
  },
  {
    deedNumber: "D049",
    sides: { North: "D050", South: "Coast", East: "Border", West: "D043" },
    deedType: { deedType: "Transfer Deed", deedNumber: "D049" },
    title: [],
    owners: [{ address: "0xopq567", share: 100 }],
    value: 1720000,
    location: [
      { longitude: 81.8, latitude: 6.9 },
      { longitude: 82.0, latitude: 6.9 },
      { longitude: 82.0, latitude: 6.7 },
      { longitude: 81.8, latitude: 6.7 },
      { longitude: 81.8, latitude: 6.9 },
    ],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Wasantha Rajapakse",
    ownerNIC: "987456789V",
    ownerAddress: "Pottuvil",
    ownerPhone: "0771748293",
    landTitleNumber: "LT-049",
    landAddress: "Coastal Trade Hub, Pottuvil",
    landArea: 49,
    landSizeUnit: "Perches",
    district: "Ampara",
    division: "Pottuvil",
    registrationDate: new Date("2021-09-14"),
  },
  {
    deedNumber: "D050",
    sides: { North: "D048", South: "D049", East: "National Park", West: "D044" },
    deedType: { deedType: "Mortgage", deedNumber: "D050" },
    title: [],
    owners: [{ address: "0xrst890", share: 100 }],
    value: 830000,
    location: [
      { longitude: 81.8, latitude: 7.1 },
      { longitude: 82.0, latitude: 7.1 },
      { longitude: 82.0, latitude: 6.9 },
      { longitude: 81.8, latitude: 6.9 },
      { longitude: 81.8, latitude: 7.1 },
    ],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Xavier Fernando",
    ownerNIC: "123654987V",
    ownerAddress: "Panama",
    ownerPhone: "0778394625",
    landTitleNumber: "LT-050",
    landAddress: "Park Border Estate, Panama",
    landArea: 73,
    landSizeUnit: "Acres",
    district: "Ampara",
    division: "Panama",
    registrationDate: new Date("2021-08-30"),
  },
];