import type { Deed } from "../types/deed";

export const mockDeeds: Deed[] = [
  {
    deedNumber: "D001",
    deedType: { deedType: "Sale", deedNumber: "D001" },
    title: [],
    owners: [{ address: "0xabc123", share: 100 }],
    value: 500000,
    location: [{ longitude: 80.2, latitude: 6.9 }],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Alice",
    ownerNIC: "123456789V",
    ownerAddress: "Colombo",
    ownerPhone: "0771234567",
    landTitleNumber: "LT-001",
    landAddress: "Main Street, Colombo",
    landArea: 20,
    landSizeUnit: "Perches",
    district: "Colombo",
    division: "Colombo 01",
    registrationDate: new Date("2025-09-01"),
  },
  {
    deedNumber: "D002",
    deedType: { deedType: "Transfer Deed", deedNumber: "D002" },
    title: [],
    owners: [{ address: "0xdef456", share: 100 }],
    value: 750000,
    location: [{ longitude: 79.8, latitude: 6.8 }],
    landType: "Lowland",
    timestamp: Date.now(),
    ownerFullName: "Bob Silva",
    ownerNIC: "987654321V",
    ownerAddress: "Kandy",
    ownerPhone: "0779876543",
    landTitleNumber: "LT-002",
    landAddress: "Temple Road, Kandy",
    landArea: 15,
    landSizeUnit: "Perches",
    district: "Kandy",
    division: "Kandy Central",
    registrationDate: new Date("2025-08-15"),
  },
  {
    deedNumber: "D003",
    deedType: { deedType: "Mortgage", deedNumber: "D003" },
    title: [],
    owners: [{ address: "0xghi789", share: 100 }],
    value: 1200000,
    location: [{ longitude: 80.0, latitude: 7.3 }],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Catherine Perera",
    ownerNIC: "456789123V",
    ownerAddress: "Galle",
    ownerPhone: "0774561238",
    landTitleNumber: "LT-003",
    landAddress: "Beach Road, Galle",
    landArea: 30,
    landSizeUnit: "Perches",
    district: "Galle",
    division: "Galle Fort",
    registrationDate: new Date("2025-07-20"),
  },
  {
    deedNumber: "D004",
    deedType: { deedType: "Sale", deedNumber: "D004" },
    title: [],
    owners: [{ address: "0xjkl012", share: 100 }],
    value: 650000,
    location: [{ longitude: 80.4, latitude: 6.7 }],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "David Fernando",
    ownerNIC: "789123456V",
    ownerAddress: "Negombo",
    ownerPhone: "0771597534",
    landTitleNumber: "LT-004",
    landAddress: "Sea Street, Negombo",
    landArea: 25,
    landSizeUnit: "Perches",
    district: "Gampaha",
    division: "Negombo",
    registrationDate: new Date("2025-06-10"),
  },
  {
    deedNumber: "D005",
    deedType: { deedType: "Transfer Deed", deedNumber: "D005" },
    title: [],
    owners: [{ address: "0xmno345", share: 100 }],
    value: 850000,
    location: [{ longitude: 81.2, latitude: 6.1 }],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Elena Rajapakse",
    ownerNIC: "321654987V",
    ownerAddress: "Matara",
    ownerPhone: "0773698741",
    landTitleNumber: "LT-005",
    landAddress: "Rice Field Lane, Matara",
    landArea: 50,
    landSizeUnit: "Acres",
    district: "Matara",
    division: "Matara South",
    registrationDate: new Date("2025-05-25"),
  },
  {
    deedNumber: "D006",
    deedType: { deedType: "Sale", deedNumber: "D006" },
    title: [],
    owners: [{ address: "0xpqr678", share: 100 }],
    value: 425000,
    location: [{ longitude: 80.6, latitude: 7.0 }],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Frank Wickramasinghe",
    ownerNIC: "654987321V",
    ownerAddress: "Kurunegala",
    ownerPhone: "0772583691",
    landTitleNumber: "LT-006",
    landAddress: "Hill View, Kurunegala",
    landArea: 18,
    landSizeUnit: "Perches",
    district: "Kurunegala",
    division: "Kurunegala East",
    registrationDate: new Date("2025-04-12"),
  },
  {
    deedNumber: "D007",
    deedType: { deedType: "Mortgage", deedNumber: "D007" },
    title: [],
    owners: [{ address: "0xstu901", share: 100 }],
    value: 970000,
    location: [{ longitude: 79.9, latitude: 6.4 }],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Grace Mendis",
    ownerNIC: "147258369V",
    ownerAddress: "Kalutara",
    ownerPhone: "0778524691",
    landTitleNumber: "LT-007",
    landAddress: "Market Square, Kalutara",
    landArea: 12,
    landSizeUnit: "Perches",
    district: "Kalutara",
    division: "Kalutara Central",
    registrationDate: new Date("2025-03-08"),
  },
  {
    deedNumber: "D008",
    deedType: { deedType: "Transfer Deed", deedNumber: "D008" },
    title: [],
    owners: [{ address: "0xvwx234", share: 100 }],
    value: 680000,
    location: [{ longitude: 80.8, latitude: 6.2 }],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Henry Gunasekara",
    ownerNIC: "963852741V",
    ownerAddress: "Hambantota",
    ownerPhone: "0774712583",
    landTitleNumber: "LT-008",
    landAddress: "Coastal Drive, Hambantota",
    landArea: 22,
    landSizeUnit: "Perches",
    district: "Hambantota",
    division: "Hambantota West",
    registrationDate: new Date("2025-02-14"),
  },
  {
    deedNumber: "D009",
    deedType: { deedType: "Sale", deedNumber: "D009" },
    title: [],
    owners: [{ address: "0xyzb567", share: 100 }],
    value: 1100000,
    location: [{ longitude: 81.0, latitude: 7.5 }],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Irene Seneviratne",
    ownerNIC: "852741963V",
    ownerAddress: "Anuradhapura",
    ownerPhone: "0776935824",
    landTitleNumber: "LT-009",
    landAddress: "Ancient City Road, Anuradhapura",
    landArea: 75,
    landSizeUnit: "Acres",
    district: "Anuradhapura",
    division: "Anuradhapura North",
    registrationDate: new Date("2025-01-30"),
  },
  {
    deedNumber: "D010",
    deedType: { deedType: "Mortgage", deedNumber: "D010" },
    title: [],
    owners: [{ address: "0xabc890", share: 100 }],
    value: 780000,
    location: [{ longitude: 80.3, latitude: 8.2 }],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Jack Amarasinghe",
    ownerNIC: "741963852V",
    ownerAddress: "Trincomalee",
    ownerPhone: "0772847193",
    landTitleNumber: "LT-010",
    landAddress: "Harbor View, Trincomalee",
    landArea: 35,
    landSizeUnit: "Perches",
    district: "Trincomalee",
    division: "Trincomalee Town",
    registrationDate: new Date("2024-12-05"),
  },
  {
    deedNumber: "D011",
    deedType: { deedType: "Sale", deedNumber: "D011" },
    title: [],
    owners: [{ address: "0xdef123", share: 100 }],
    value: 590000,
    location: [{ longitude: 80.7, latitude: 9.1 }],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Karen Jayawardene",
    ownerNIC: "159357248V",
    ownerAddress: "Jaffna",
    ownerPhone: "0779518264",
    landTitleNumber: "LT-011",
    landAddress: "Temple Street, Jaffna",
    landArea: 19,
    landSizeUnit: "Perches",
    district: "Jaffna",
    division: "Jaffna Central",
    registrationDate: new Date("2024-11-18"),
  },
  {
    deedNumber: "D012",
    deedType: { deedType: "Transfer Deed", deedNumber: "D012" },
    title: [],
    owners: [{ address: "0xghi456", share: 100 }],
    value: 920000,
    location: [{ longitude: 81.5, latitude: 6.5 }],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Louis Dissanayake",
    ownerNIC: "357248159V",
    ownerAddress: "Batticaloa",
    ownerPhone: "0773628517",
    landTitleNumber: "LT-012",
    landAddress: "Lagoon Road, Batticaloa",
    landArea: 28,
    landSizeUnit: "Perches",
    district: "Batticaloa",
    division: "Batticaloa East",
    registrationDate: new Date("2024-10-22"),
  },
  {
    deedNumber: "D013",
    deedType: { deedType: "Sale", deedNumber: "D013" },
    title: [],
    owners: [{ address: "0xjkl789", share: 100 }],
    value: 460000,
    location: [{ longitude: 80.1, latitude: 7.8 }],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Maria Karunaratne",
    ownerNIC: "248159357V",
    ownerAddress: "Puttalam",
    ownerPhone: "0775197382",
    landTitleNumber: "LT-013",
    landAddress: "Coconut Grove, Puttalam",
    landArea: 40,
    landSizeUnit: "Acres",
    district: "Puttalam",
    division: "Puttalam South",
    registrationDate: new Date("2024-09-15"),
  },
  {
    deedNumber: "D014",
    deedType: { deedType: "Mortgage", deedNumber: "D014" },
    title: [],
    owners: [{ address: "0xmno012", share: 100 }],
    value: 810000,
    location: [{ longitude: 80.5, latitude: 5.9 }],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Nathan Wijeratne",
    ownerNIC: "159248357V",
    ownerAddress: "Ratnapura",
    ownerPhone: "0778462139",
    landTitleNumber: "LT-014",
    landAddress: "Gem Valley, Ratnapura",
    landArea: 33,
    landSizeUnit: "Perches",
    district: "Ratnapura",
    division: "Ratnapura Central",
    registrationDate: new Date("2024-08-28"),
  },
  {
    deedNumber: "D015",
    deedType: { deedType: "Transfer Deed", deedNumber: "D015" },
    title: [],
    owners: [{ address: "0xpqr345", share: 100 }],
    value: 675000,
    location: [{ longitude: 80.9, latitude: 6.8 }],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Olivia Samaraweera",
    ownerNIC: "357159248V",
    ownerAddress: "Kegalle",
    ownerPhone: "0772639841",
    landTitleNumber: "LT-015",
    landAddress: "Mountain View, Kegalle",
    landArea: 21,
    landSizeUnit: "Perches",
    district: "Kegalle",
    division: "Kegalle North",
    registrationDate: new Date("2024-07-11"),
  },
  {
    deedNumber: "D016",
    deedType: { deedType: "Sale", deedNumber: "D016" },
    title: [],
    owners: [{ address: "0xstu678", share: 100 }],
    value: 1150000,
    location: [{ longitude: 81.3, latitude: 7.2 }],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Peter Ranasinghe",
    ownerNIC: "248357159V",
    ownerAddress: "Polonnaruwa",
    ownerPhone: "0776281534",
    landTitleNumber: "LT-016",
    landAddress: "Heritage Plaza, Polonnaruwa",
    landArea: 14,
    landSizeUnit: "Perches",
    district: "Polonnaruwa",
    division: "Polonnaruwa Town",
    registrationDate: new Date("2024-06-03"),
  },
  {
    deedNumber: "D017",
    deedType: { deedType: "Mortgage", deedNumber: "D017" },
    title: [],
    owners: [{ address: "0xvwx901", share: 100 }],
    value: 520000,
    location: [{ longitude: 80.4, latitude: 9.7 }],
    landType: "Agricultural",
    timestamp: Date.now(),
    ownerFullName: "Quinn Bandara",
    ownerNIC: "159357248V",
    ownerAddress: "Mannar",
    ownerPhone: "0779753168",
    landTitleNumber: "LT-017",
    landAddress: "Fishery Lane, Mannar",
    landArea: 60,
    landSizeUnit: "Acres",
    district: "Mannar",
    division: "Mannar Island",
    registrationDate: new Date("2024-05-19"),
  },
  {
    deedNumber: "D018",
    deedType: { deedType: "Transfer Deed", deedNumber: "D018" },
    title: [],
    owners: [{ address: "0xyzb234", share: 100 }],
    value: 790000,
    location: [{ longitude: 80.2, latitude: 8.5 }],
    landType: "Highland",
    timestamp: Date.now(),
    ownerFullName: "Rachel Vithanage",
    ownerNIC: "357248159V",
    ownerAddress: "Vavuniya",
    ownerPhone: "0774816239",
    landTitleNumber: "LT-018",
    landAddress: "Forest Edge, Vavuniya",
    landArea: 27,
    landSizeUnit: "Perches",
    district: "Vavuniya",
    division: "Vavuniya South",
    registrationDate: new Date("2024-04-06"),
  },
  {
    deedNumber: "D019",
    deedType: { deedType: "Sale", deedNumber: "D019" },
    title: [],
    owners: [{ address: "0xabc567", share: 100 }],
    value: 640000,
    location: [{ longitude: 81.1, latitude: 8.8 }],
    landType: "Residential",
    timestamp: Date.now(),
    ownerFullName: "Samuel Liyanage",
    ownerNIC: "248159357V",
    ownerAddress: "Kilinochchi",
    ownerPhone: "0771594826",
    landTitleNumber: "LT-019",
    landAddress: "Peace Road, Kilinochchi",
    landArea: 16,
    landSizeUnit: "Perches",
    district: "Kilinochchi",
    division: "Kilinochchi Central",
    registrationDate: new Date("2024-03-21"),
  },
  {
    deedNumber: "D020",
    deedType: { deedType: "Mortgage", deedNumber: "D020" },
    title: [],
    owners: [{ address: "0xdef890", share: 100 }],
    value: 880000,
    location: [{ longitude: 80.6, latitude: 9.3 }],
    landType: "Commercial",
    timestamp: Date.now(),
    ownerFullName: "Tanya Senanayake",
    ownerNIC: "159357248V",
    ownerAddress: "Mullaitivu",
    ownerPhone: "0778629415",
    landTitleNumber: "LT-020",
    landAddress: "Harbor Front, Mullaitivu",
    landArea: 24,
    landSizeUnit: "Perches",
    district: "Mullaitivu",
    division: "Mullaitivu North",
    registrationDate: new Date("2024-02-07"),
  },
];