name: CI/CD Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rasindudulshansiriwardhana/department-client-web
      DOCKER_COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg VITE_USER_API_URL=${{ secrets.VITE_USER_API_URL }} \
            --build-arg VITE_DEED_API_URL=${{ secrets.VITE_DEED_API_URL }} \
            --build-arg VITE_PINATA_API_URL=${{ secrets.VITE_PINATA_API_URL }} \
            --build-arg VITE_SURVEY_PLAN_API_URL=${{ secrets.VITE_SURVEY_PLAN_API_URL }} \
            --build-arg VITE_PROPERTY_NFT_ADDRESS=${{ secrets.VITE_PROPERTY_NFT_ADDRESS }} \
            --build-arg VITE_FACTORY_ADDRESS=${{ secrets.VITE_FACTORY_ADDRESS }} \
            --build-arg VITE_FRACTIONAL_ADDESS=${{ secrets.VITE_FRACTIONAL_ADDESS }} \
            --build-arg VITE_ESCROW_FACTORY_ADDRESS=${{ secrets.VITE_ESCROW_FACTORY_ADDRESS }} \
            --build-arg VITE_DEPLOYER_ADDRESS=${{ secrets.VITE_DEPLOYER_ADDRESS }} \
            -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f $DOCKER_COMPOSE_FILE pull
          docker-compose -f $DOCKER_COMPOSE_FILE up -d --remove-orphans
