name: CI/CD Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rasindudulshansiriwardhana/department-client-web
      CONTAINER_NAME: department-client-web
      DOCKER_COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f $DOCKER_COMPOSE_FILE pull
          docker-compose -f $DOCKER_COMPOSE_FILE up -d --remove-orphans
